version: '3'
 
services:

  mysql:
    build: services/mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./services/mysql/data/:/var/lib/mysql
    ports:
      - 1106:3306

  nginx:
    build: services/nginx
    container_name: nginx
    restart: always
    working_dir: /www
    volumes:
      - ./web:/www
    ports:
      - 1180:80

  phpfpm:
    build: services/phpfpm
    container_name: phpfpm
    restart: always
    working_dir: /www
    volumes:
      - ./web:/www
